---
title: "Systems"
author: "Adrien Bouisson"
format: html
editor: visual
---
execute: 
  echo: false
  warning: false
  error: false

I upload all packages for the exercise

```{r}
library(dplyr)
library(tidyr)
library(vroom)
library(ggplot2)
library(here)
library(knitr)
library(stringr)
```

```{r}
here::i_am("systems.Rproj")
```

# Question 1 

I clearly uploaded everything before reading to fixed it, like that i can have all data files and i will commit only the main data file in my repository. 

# Question 2 

link to my github's repository : https://github.com/adribsn/systems

# Question 3 

```{r}
systems <- vroom(here("the_systems.csv"), na = '_') 

num_systems <- nrow(systems)
num_variables <- ncol(systems)
numerical_variables <- sum(sapply(systems, is.numeric))

# Validation message by using if / else

if (num_systems == 1085 && num_variables == 8 && numerical_variables == 2) {
  cat("Data loaded successfully!")
} else {
  cat("Error: Invalid loading process.")
}
systems |> select(where(is.numeric))

head_systems <- systems %>%
  head(n=100) # We use head_df tbecause it allows you to quickly visualize the first observations of a dataset.

```




